id: P300547FD
initial_creation_type: input
source_metadata:
  title: Lhatsün Namkha Jigme Series
  language: fr
  description: 'Texts associated with the famous yogi Lhatsün Namkha Jigme (lha btsun
    nam mkha'' ''jigs med, 1597–1650), who is credited with ''opening the hidden land''
    of Sikkim:'
  volume:
    8bf34094714a4766a0f51a21c3728729:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    bd5348d559544846b1e42e117f7cc87f:
      title: Summoning Prosperity
      parent: Prayers and Practices
    7971cb6d26eb48d98e936eb8cd16808b:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Sang Offering
    65aa181e41a844dc989cfecdbba6ac22:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Sang Offering
    fcf63a523e1147d7b1b1ee45514ff2ab:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
created_at: '2022-03-01T00:35:25.497679'
last_modified_at: '2022-03-01T00:35:25.497682'
